# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JetStream
email: malte.vesper@manchester.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  JetStream - a PCIe FPGA solution with host-to-FPGA and FPGA-to_FPGA communication.
baseurl: "/JetStream" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  maltevesper

# Build settings
markdown: kramdown

port: 3000 #change server port for testing

gems:
  - jekyll-feed